apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sock-shop-ingress
  namespace: sock-shop
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: socks.royalboe.live
    http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: front-end-svc
              port:
                number: 80