apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-persistent-volume-claim
  labels:
    app: prometheus-deployment
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500i
