apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: note-app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: fhsinchy/notes-api:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "150Mi"
              cpu: "300m"
          envFrom:
            - configMapRef:
                name: api-config-map
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
      restartPolicy: Always